running laravel octane as a php process instead of using supervisor

diff --git a/deployment/start-container b/deployment/start-container
--- a/deployment/start-container
+++ b/deployment/start-container
@@ -58,3 +58,8 @@ elif [ ${container_mode} = "http" ]; then
         echo "Invalid Octane server supplied."
         exit 1
     fi
+else
+    echo "Invalid container mode supplied."
+    exit 1
+fi
+
